# Generated by Django 3.1.1 on 2020-09-10 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('answer_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('answer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('correct_answer', models.ManyToManyField(blank=True, related_name='correct_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
